---
# handlers file for ansible-role-galaxycloud-tools

- name: restart galaxy
  command: "/usr/bin/galaxyctl restart galaxy --force"
  ignore_errors: yes

- name: start galaxy
  command: "/usr/bin/galaxyctl start galaxy --force"
  ignore_errors: yes
  when: ansible_virtualization_type != "docker"
